### ISSUE TITLE
Wav file does not play (mac M2)

### ISSUE THREAD

**Issue by CrumpLab** [jeroen/miditools#2]
Thanks for developing this package!!!

Issue:

The .wav file from `midi_convert()` does not play. Here's the code I'm using. `midi_play()` works on this midi file and plays it using the soundfont on my machine.

```
midi_convert(
  midi = "the-moon.mid",
  soundfont = "~/Library/Audio/Sounds/Banks/FluidR3_GM.sf2",
  output = "output.wav",
  settings = list(),
  progress = interactive()
)
```

The wav file is generated, but is not playable. I think it may be in a RAW format. {av::av_audio_convert} will convert the wav file to a listenable mp3.

I had previously installed fluidsynth with homebrew. I had a similar problem with producing listenable wav files when running fluidsynth from the terminal. I believe I solved that issue by installing libsndfile.

I have to run to a meeting, but will add more info soon.

Thanks again for this package!

**Comment by CrumpLab** [comment]
I rendered `All_Night_Long.mid` contained in {fluidsynth}

```
midi <- system.file("generaluser-gs/midi/All_Night_Long.mid", package = "fluidsynth")
wav <- fluidsynth::midi_convert(midi, output = 'test.wav')
av::av_audio_convert("test.wav", "test.mp3")
```

The mp3 plays fine, but the wav file does not play. I should be more specific that the wav file does not play from the mac os finder with a quick preview. And, the wav file will not open in Quicktime.

The wav file does open up in Adobe Audition with an error message "Warning: This file was recovered from an unfinished recording or an interrupted save". The wav will play in adobe audition after clicking through the error message. It appears to be a 44100 hz, 16-bit Stereo file.

**Comment by jeroen** [comment]
I think you are right that `fluidsynth` will export raw s16 audio when it does  support the requested output format or when it does not find `libsndfile`. Does it make a difference if you use `.flac` instead of `.mp3` ?

I think the binaries that you install from https://ropensci.r-universe.dev/fluidsynth should have libsndfile (and also those from homebrew I think, so there may be something weird here).

**Comment by CrumpLab** [comment]
A few more tidbits. 

I tried installing {fluidsynth} on an older intel mac, where I had not previously installed any version of fluidsynth or libsndfile. The installation went fine, {fluidsynth} appeared to work fine. I was able to render a wav file using the code from above. However, the wav file was not playable by quicktime.

On the mac M2 laptop, I tried rendering to wav, flac, and aiff. All three filetypes were created. The aiff and wav files are not recognized by quicktime. However, all three play fine in vlc. 

I suspect even though these files have different file extensions, that they are all actually in RAW format, and that libsndfile is not working for me

Practically I'm going to convert to mp3 straightaway using {av}, and that works fine which is great.

**Comment by jeroen** [comment]
OK I think the safest approach is just that we automatically convert the file generated by fluidsynth to the desired output file and format using av, instead of letting the user do this manually. I changed it so now you can just do:

```r
midi_convert("input.midi, output = "output.mp3")
```

And this will automatically do both steps.
